root@conforti:/home/ubuntu/master# python3 serverCoAP.py 
172.16.4.232
172.16.4.4
/usr/bin/time -p -o info.txt -a runc checkpoint --image-path image  python_bundle
/usr/bin/time -p -o info.txt -a runc checkpoint --image-path image  python_bundle finished after 0.61 second(s) with 0
DUMP size: 29M	/runc/containers/python_bundle/image

Number of files: 48 (reg: 47, dir: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 47
Total file size: 29.58M bytes
Total transferred file size: 29.58M bytes
Literal data: 28.88M bytes
Matched data: 702.02K bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 6.49M
Total bytes received: 34.10K

sent 6.49M bytes  received 34.10K bytes  1.86M bytes/sec
total size is 29.58M  speedup is 4.53
172.16.4.232
172.16.4.4
/usr/bin/time -p -o info.txt -a runc checkpoint --image-path image  python_bundle
/usr/bin/time -p -o info.txt -a runc checkpoint --image-path image  python_bundle finished after 0.02 second(s) with 1
Something did not work. Exiting!
time="2021-09-19T01:14:24Z" level=error msg="container \"python_bundle\" does not exist"
container "python_bundle" does not exist
Transferring DUMP to 172.16.4.232
DUMP transfer time 2.31891584396 seconds
runc restored python_bundle successfully